// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PackageFlow.Data.Context;

#nullable disable

namespace PackageFlow.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260913164627_change_postal_code_data_type")]
    partial class change_postal_code_data_type
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.31");

            modelBuilder.Entity("PackageFlow.Core.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.Property<string>("VehiclePlateNumber")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PackageFlow.Core.Models.Package", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeliveredAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DeliveryCourierId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("OutForDeliveryAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PickedUpAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PickupCourierId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ReceivedInWarehouseAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("RecipientEmail")
                        .HasColumnType("TEXT");

                    b.Property<string>("RecipientName")
                        .HasColumnType("TEXT");

                    b.Property<string>("RecipientPhone")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RecipientUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("ScheduledPickupDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("SenderEmail")
                        .HasColumnType("TEXT");

                    b.Property<string>("SenderName")
                        .HasColumnType("TEXT");

                    b.Property<string>("SenderPhone")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SenderUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Size")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TrackingNumber")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int?>("WarehouseId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("WeightKg")
                        .HasPrecision(6, 2)
                        .HasColumnType("TEXT");

                    b.ComplexProperty<Dictionary<string, object>>("DeliveryAddress", "PackageFlow.Core.Models.Package.DeliveryAddress#Address", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("BuildingDetails")
                                .HasColumnType("TEXT");

                            b1.Property<string>("City")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Country")
                                .HasColumnType("TEXT");

                            b1.Property<int>("PostalCode")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("State")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Street")
                                .HasColumnType("TEXT");

                            b1.Property<int>("StreetNumber")
                                .HasColumnType("INTEGER");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("SenderAddress", "PackageFlow.Core.Models.Package.SenderAddress#Address", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("BuildingDetails")
                                .HasColumnType("TEXT");

                            b1.Property<string>("City")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Country")
                                .HasColumnType("TEXT");

                            b1.Property<int>("PostalCode")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("State")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Street")
                                .HasColumnType("TEXT");

                            b1.Property<int>("StreetNumber")
                                .HasColumnType("INTEGER");
                        });

                    b.HasKey("Id");

                    b.HasIndex("DeliveryCourierId");

                    b.HasIndex("PickupCourierId");

                    b.HasIndex("RecipientUserId");

                    b.HasIndex("ScheduledPickupDate");

                    b.HasIndex("SenderUserId");

                    b.HasIndex("Status");

                    b.HasIndex("TrackingNumber")
                        .IsUnique();

                    b.HasIndex("WarehouseId");

                    b.ToTable("Packages");
                });

            modelBuilder.Entity("PackageFlow.Core.Models.PackageStatusHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ChangedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<int>("PackageId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChangedByUserId");

                    b.HasIndex("PackageId");

                    b.HasIndex("Timestamp");

                    b.ToTable("PackageStatusHistories");
                });

            modelBuilder.Entity("PackageFlow.Core.Models.Warehouse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxCapacity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(500);

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.ComplexProperty<Dictionary<string, object>>("Address", "PackageFlow.Core.Models.Warehouse.Address#Address", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("BuildingDetails")
                                .HasColumnType("TEXT");

                            b1.Property<string>("City")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Country")
                                .HasColumnType("TEXT");

                            b1.Property<int>("PostalCode")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("State")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Street")
                                .HasColumnType("TEXT");

                            b1.Property<int>("StreetNumber")
                                .HasColumnType("INTEGER");
                        });

                    b.HasKey("Id");

                    b.ToTable("Warehouses");
                });

            modelBuilder.Entity("PackageFlow.Core.Models.WarehouseCapacityLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentPackageCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LoggedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxCapacitySnapshot")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LoggedAt");

                    b.HasIndex("WarehouseId");

                    b.ToTable("WarehouseCapacityLogs");
                });

            modelBuilder.Entity("PackageFlow.Core.Models.Package", b =>
                {
                    b.HasOne("PackageFlow.Core.Models.AppUser", "DeliveryCourier")
                        .WithMany("DeliveryAssignedPackages")
                        .HasForeignKey("DeliveryCourierId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PackageFlow.Core.Models.AppUser", "PickupCourier")
                        .WithMany("PickupAssignedPackages")
                        .HasForeignKey("PickupCourierId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PackageFlow.Core.Models.AppUser", "RecipientUser")
                        .WithMany("ReceivedPackages")
                        .HasForeignKey("RecipientUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PackageFlow.Core.Models.AppUser", "SenderUser")
                        .WithMany("SentPackages")
                        .HasForeignKey("SenderUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PackageFlow.Core.Models.Warehouse", "Warehouse")
                        .WithMany("StoredPackages")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("DeliveryCourier");

                    b.Navigation("PickupCourier");

                    b.Navigation("RecipientUser");

                    b.Navigation("SenderUser");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("PackageFlow.Core.Models.PackageStatusHistory", b =>
                {
                    b.HasOne("PackageFlow.Core.Models.AppUser", "ChangedByUser")
                        .WithMany()
                        .HasForeignKey("ChangedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PackageFlow.Core.Models.Package", "Package")
                        .WithMany("StatusHistory")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChangedByUser");

                    b.Navigation("Package");
                });

            modelBuilder.Entity("PackageFlow.Core.Models.WarehouseCapacityLog", b =>
                {
                    b.HasOne("PackageFlow.Core.Models.Warehouse", "Warehouse")
                        .WithMany("CapacityLogs")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("PackageFlow.Core.Models.AppUser", b =>
                {
                    b.Navigation("DeliveryAssignedPackages");

                    b.Navigation("PickupAssignedPackages");

                    b.Navigation("ReceivedPackages");

                    b.Navigation("SentPackages");
                });

            modelBuilder.Entity("PackageFlow.Core.Models.Package", b =>
                {
                    b.Navigation("StatusHistory");
                });

            modelBuilder.Entity("PackageFlow.Core.Models.Warehouse", b =>
                {
                    b.Navigation("CapacityLogs");

                    b.Navigation("StoredPackages");
                });
#pragma warning restore 612, 618
        }
    }
}
